### ISSUE TITLE
Deprecation warnings from transitively-referenced `actions/setup-dotnet`

### ISSUE THREAD

**Issue by bdach** [JetBrains/ReSharper-InspectCode#10]
I'm exploring the possibility of replacing manual usage of InspectCode the CLI tool with this action in CI contexts. This action pulls in `actions/setup-dotnet@v3.0.3`:

https://github.com/JetBrains/ReSharper-InspectCode/blob/311bfd9f169bd2f344ed80bc095d34a5fb63ec99/action.yml#L94

which raises deprecation warnings:

```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-dotnet@v3.0.3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

Would be trivial to bump myself, but I figure it's probably proper manners to ask first.

**Comment by derigel23** [comment]
Hi @bdach!
Fixed in v0.8
